# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinox_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
