# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinox_api', '0004_operation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='new_att',
            field=models.BooleanField(default=True),
        ),
    ]
