# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinox_api', '0006_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
